MediaRequest/ViewModels/Television/SeasonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaRequest.WebUI.ViewModels.Television
{
    public class SeasonViewModel
    {
        public int Number { get; set; }
        public string Name { get; set; }
        public bool Monitored { get; set; }
        public int TvdbId { get; set; }
        public string Overview { get; set; }
        public int MyProperty { get; set; }
    }
}

MediaRequest/ViewModels/Television/SeriesCreditViewModel.cs
using MediaRequest.Domain.API_Responses.TvMaze;
using MediaRequest.Domain.TMDB;
using MediaRequest.WebUI.Business.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaRequest.WebUI.ViewModels.Television
{
    public class SeriesCreditViewModel
    {
        private IEnumerable<Cast> _cast;
        private IEnumerable<Cast> _topBilled;

        public SeriesCreditViewModel(IEnumerable<Cast> sourceCast, int creditRows = 3)
        {
            _topBilled = sourceCast.ToList().GetRange(0, sourceCast.Count() > 5 ? 5 : sourceCast.Count());
            _cast = sourceCast.Skip(5).TakeRows(3);
        }

        public int TvMazeId { get; set; }
        public IEnumerable<Cast> Cast => _cast;
        public IEnumerable<Cast> TopBilled => _topBilled;
    }
}

MediaRequest/ViewModels/Television/SeriesViewModel.cs
using MediaRequest.Domain.API_Responses.TvMaze;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SonarrSeries = MediaRequest.Domain.API_Responses.Sonarr.Series;
using TMDBSeries = MediaRequest.Domain.API_Responses.TMDB.Series;

namespace MediaRequest.WebUI.ViewModels.Television
{
    public class SeriesViewModel
    {
        public bool Requested { get; set; }
        public bool Accepted { get; set; }
        public bool AlreadyAdded => SonarrSeries.Added == DateTime.MinValue ? false : true;

        public SonarrSeries SonarrSeries { get; set; }
        public TMDBSeries TmdbSeries { get; set; }
        public SeriesCreditViewModel Cast { get; set; }
    }
}

MediaRequest/ViewModels/Television/TelevisionActorViewModel.cs
using MediaRequest.Domain.API_Responses.TvMaze;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaRequest.WebUI.ViewModels.Television
{
    public class TelevisionActorViewModel
    {
        public Person Actor { get; set; }
        public IEnumerable<PersonCredit> Credits { get; set; }
    }
}

MediaRequest/Controllers/MovieController.cs
using MediaRequest.Application.Queries.Movies;
using MediaRequest.Application.Queries.People.GetPopularMovies;
using MediaRequest.Application.Queries.Requests.GetSingleRequest;
using MediaRequest.Domain;
using MediaRequest.Domain.Interfaces;
using MediaRequest.WebUI.Models.IdentityModels;
using MediaRequest.WebUI.ViewModels;
using MediaRequest.WebUI.ViewModels.SingleMovie;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaRequest.Controllers
{
    [Authorize]
    public class MovieController : Controller
    {
        private readonly IMediator _mediator;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMemoryCache _memoryCache;

        public MovieController(IMediator mediator, UserManager<ApplicationUser> userManager, IMemoryCache memoryCache)
        {
            _mediator = mediator;
            _userManager = userManager;
            _memoryCache = memoryCache;
        }

        [Route("movie/{slug}")]
        [ResponseCache(Duration = 180, Location = ResponseCacheLocation.Any)]
        public async Task<IActionResult> Show(string slug)
        {
            var result = await _mediator.Send(new GetSingleMovieRequest() { TmdbId = slug.Split('-').Last() });
            var existing = await _mediator.Send(new GetExistingMoviesRequest());
            var currentUser = _userManager.GetUserId(User);

            if (existing.Movies.Any(x => x.TmdbId == result.Movie.TmdbId))
            {
                result.Movie.HasFile = true;
            }

            var requested = await _mediator.Send(new RequestExistsRequest { Movie = result.Movie, UserId = currentUser });

            var model = new MovieViewModel();
            model.Movie = result.Movie;
            model.Requested = requested.Exists;

            return View(model);
        }

        public IActionResult Trailer(string ytid)
        {
            return PartialView("_TrailerPartial", ytid);
        }

        [Route("movie/credits")]
        public async Task<IActionResult> Credits(string tmdbid, int? amount)
        {
            var response = await _mediator.Send(new GetCreditsRequest { TMDBId = tmdbid, Amount = amount ?? 0 });
            var model = new MovieCreditsViewModel(response.Credits) { TMDBId = tmdbid };

            return PartialView("_CreditsPartial", model);
        }

        [Route("movie/recommendations")]
        public async Task<IActionResult> Recommendations(string tmdbid)
        {
            var response = await _mediator.Send(new GetRecommendedRequest { TMDBId = tmdbid, Page = 1 });
            var model = response.Recommendations;
            model.TmdbId = tmdbid;

            return PartialView("_RecommendationsPartial", model);
        }

        private async Task<IEnumerable<IMediaType>> GetPreviousWorks(string actorId)
        {
            var movies = await _mediator.Send(new GetPopularMoviesRequest { ActorId = actorId, MediaType = MediaType.Movie });
            var series = await _mediator.Send(new GetPopularMoviesRequest { ActorId = actorId, MediaType = MediaType.Tv });

            var joined = new List<IMediaType>();
            joined.Concat(movies.Movies as IEnumerable<IMediaType>);
            joined.Concat(series.Movies as IEnumerable<IMediaType>);

            //joined.OrderBy(x => x.)

            return joined;
        }
    }
}

MediaRequest/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediaRequest.Application;
using MediaRequest.Application.Commands;
using MediaRequest.Application.Commands.ApproveRequest;
using MediaRequest.Application.Commands.CancelRequest;
using MediaRequest.Application.Queries.Movies;
using MediaRequest.Domain;
using MediaRequest.Domain.API_Responses.Radarr.v3;
using MediaRequest.WebUI.Models.IdentityModels;
using MediaRequest.WebUI.ViewModels.SingleMovie;
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MediaRequest.WebUI.Controllers
{
    public class RequestController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMediaDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public RequestController(IMediator mediator, IMediaDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _mediator = mediator;
        }


        public async Task<IActionResult> AddRequest(string tmdbid)
        {
            var requests = await _context.Request.ToListAsync();
            var currentUser = await _userManager.GetUserAsync(User);
            
            var movie = await _mediator.Send(new GetSingleMovieRequest { TmdbId = tmdbid });

            if (await _context.Request.Where(x => x.UserId == currentUser.Id && x.MovieId == tmdbid).CountAsync() > 0)
            {
                return RedirectToAction("Show", "Movie", new { slug = movie.Movie.TitleSlug });
            }
                
            var command = new AddRequestCommand
            {
                Request = new UserRequest()
                {
                    Status = false,
                    MovieId = tmdbid,
                    UserId = currentUser.Id
                }
            };

            await _mediator.Send(command);
            return RedirectToAction("Show", "Movie", new { slug = movie.Movie.TitleSlug });
        }

        public async Task<IActionResult> ApproveRequest(string id)
        {
            //var userRequest = await _context.Request.SingleOrDefaultAsync(x => x.Id == requestId);
            var requests = _context.Request.Where(x => x.MovieId == id);

            var movie = await _mediator.Send(new GetSingleMovieRequest() { TmdbId = id });
            var request = GenerateApproveRequest(movie.Movie);

            var command = new ApproveRequestCommand { RequestObject = request };
            var result = await _mediator.Send(command);

            if (result == true)
            {
                //userRequest.Status = true;
                await requests.ForEachAsync(x => x.Status = true);
                await _context.SaveChangesAsync();
            }
            else
            {
                //userRequest.Status = false;
                await requests.ForEachAsync(x => x.Status = false);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Requests", "Admin");
        }

        public async Task<IActionResult> CancelRequest(int requestid)
        {
            if(ModelState.IsValid)
            {
                var command = new CancelRequestCommand { RequestID = requestid };
                try
                {
                    var response = await _mediator.Send(command);
                }
                catch (Exception ex)
                {
                    TempData["Error"] = ex.Message;
                    return RedirectToAction("Profile", "User");
                }

                TempData["Success"] = "Request succesfully removed";
                return RedirectToAction("Profile", "User");
            } else
            {
                TempData["Error"] = "Invalid operation";
                return RedirectToAction("Profile", "User");
            }
        }

        [HttpGet]
        public IActionResult AddMovie()
        {
            HttpContext.Response.StatusCode = 405;
            return RedirectToAction("Error", "Home");
        }

        /// <summary>
        ///     Lets admins add movies directly, bypassing the need for requests
        /// </summary>
        /// <param name="tmdb"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AddMovie(string tmdbid)
        {
            var movie = await _mediator.Send(new GetSingleMovieRequest() { TmdbId = tmdbid });
            var request = GenerateApproveRequest(movie.Movie);


            var command = new ApproveRequestCommand { RequestObject = request };
            var result = await _mediator.Send(command);

            var model = new MovieViewModel { Movie = movie.Movie, Accepted = result, Requested = result };

            if (result)
                TempData["Success"] = "Movie added";
            else
                TempData["Error"] = "There was an error adding the movie";

            return PartialView("_RequestMovieButton", model);
        }

        private MovieRequestObject GenerateApproveRequest(Movie movie)
        {
            var request = new MovieRequestObject()
            {
                title = movie.Title,
                qualityProfileId = 4,
                images = movie.Images,
                tmdbId = movie.TmdbId.ToString(),
                titleSlug = movie.Slug,
                ProfileId = 4,
                year = movie.Year,
                path = $"/home34/robert/downloads/movies/{movie.Title} ({movie.Year})".Replace(":", ""),
                addOptions = new MovieRequestObjectOptions
                {
                    searchForMovie = "true"
                }
            };

            return request;
        }
    }
}

MediaRequest/Controllers/TelevisionController.cs
namespace MediaRequest.WebUI.Controllers
{
    using MediaRequest.Application.Queries.Find;
    using MediaRequest.Application.Queries.Movies;
    using MediaRequest.Application.Queries.Television;
    using MediaRequest.Application.Queries.Television.Sonarr;
    using MediaRequest.WebUI.ViewModels.Television;
    using MediatR;
    using Microsoft.AspNetCore.Mvc;
    using System.Linq;
    using System.Threading.Tasks;

    public class TelevisionController : Controller
    {
        private readonly IMediator _mediator;

        public TelevisionController(IMediator mediator)
        {
            _mediator = mediator;
        }

        [Route("television")]
        public async Task<IActionResult> Index()
        {
            var response = await _mediator.Send(new GetAllSeriesRequest());

            return View(response.Series);
        }

        [Route("television/{slug}")]
        public async Task<IActionResult> Show(string slug)
        {

            var tvdbId = slug.Split('-').LastOrDefault();

            //var sonarrSeries = await _mediator.Send(new LookupSeriesByIdRequest() { Id = tvdbId });
            var sonarrSeries = await _mediator.Send(new GetSingleSeriesByTvdbIdRequest { TvdbId = tvdbId });
            var tmdbLookup = await _mediator.Send(new SearchByExternalIdRequest() { Id = tvdbId, Source = ExternalSource.TVDB });

            var tmdbId = tmdbLookup.Result.TvResults.FirstOrDefault()?.Id.ToString();

            var tmdbSeries = await _mediator.Send(new Application.Queries.TMDB.GetSingleSeriesRequest(tmdbId));
            var cast = await _mediator.Send(new GetCreditsRequest() { TMDBId = tmdbSeries.Series.Id.ToString(), MediaType = Domain.MediaType.Tv });

            var model = new SeriesViewModel();

            if (sonarrSeries.Series != null)
            {
                model.SonarrSeries = sonarrSeries.Series;
                model.TmdbSeries = tmdbSeries.Series;
                model.Cast = new SeriesCreditViewModel(cast.Credits.Cast);

                //if (tmdbLookup.Result.TvResults.Any())
                //{
                //    var cast = await _mediator.Send(new GetCreditsRequest() { TMDBId = tmdbSeries.Result.TvResults.FirstOrDefault()?.Id.ToString(), MediaType = Domain.MediaType.Tv });
                //    model.Cast = new SeriesCreditViewModel(cast.Credits.Cast);
                //}
            }

            return View(model);
        }

        //[Route("television/actor/{slug}")]
        //public async Task<IActionResult> Actor(string slug)
        //{
        //    var mazeId = slug.Split("-").LastOrDefault();

        //    var actor = await _mediator.Send(new GetActorRequest(mazeId));
        //    var credits = await _mediator.Send(new GetActorWithCreditsRequest(mazeId));

        //    var model = new TelevisionActorViewModel()
        //    {
        //        Actor = actor.Actor,
        //        Credits = credits.Credits
        //    };

        //    return View(model);
        //}
    }
}

MediaRequest/Views/Television/Index.cshtml
@model IEnumerable<MediaRequest.Domain.API_Responses.Sonarr.Series>

@{
    Layout = "~/Views/Shared/Layouts/_Base.cshtml";
}

<div class="container px-xs-1 px-sm-2 wide grid-layout grid-col-xs-2 grid-col-md-3 grid-col-lg-4 grid-col-xl-5 grid-gap-xs-1 grid-gap-sm-2">

    @foreach (var show in Model.OrderBy(x => x.Title))
    {
        <a class="television-card" asp-controller="television" asp-action="show" asp-route-slug="@show.Slug">
            <div class="card-head">
                <div class="status-container">


                    @if (show.Monitored)
                    {
                        <span class="badge badge-sm badge-success">Monitored</span>
                    }
                    else
                    {
                        <span class="badge badge-sm badge-danger">Not Monitored</span>
                    }

                    

                </div>
                <partial name="_Poster" model="show" />
            </div>
            <div class="card-body">
                <h2 class="title">@show.Title</h2>
                <div class="d-block mb-1">
                    @if (show.EpisodeFileCount > 0)
                    {
                        var episodeStatus = "";
                        if (show.EpisodeFileCount == 0) { episodeStatus = "danger"; }
                        else if (show.EpisodeFileCount < show.EpisodeCount) { episodeStatus = "warning"; }
                        else if (show.EpisodeFileCount == show.EpisodeCount) { episodeStatus = "success"; };

                        <span class="badge badge-sm badge-@episodeStatus">@show.EpisodeFileCount/@show.EpisodeCount</span>
                    }

                    @if (show.Status == "continuing")
                    {
                        <span class="badge badge-sm badge-success">Continuing</span>
                    }
                    else
                    {
                        <span class="badge badge-sm badge-danger">Ended</span>
                    }
                </div>

                <p class="description">@show.Overview</p>
            </div>
        </a>
    }
</div>

MediaRequest/Views/Television/Series.cshtml
@model MediaRequest.WebUI.ViewModels.Television.SeriesViewModel

<div class="single-movie-container" id="main-container">
    <div class="hero-container">
        <img class="background" src="@(Model.Series.Images.SingleOrDefault(x => x.CoverType == "fanart").Url)" />
    </div>
    <section class="container">
        <div class="head">
            <div class="poster">
                <img src="@(Model.Series.Images.SingleOrDefault(x => x.CoverType == "poster").Url)">
            </div>
            <div class="info">
                <div class="title">
                    <h1 style="color:#222;">@Model.Series.Title</h1>
                    <div class="trivia">
                        <ul>
                            <li>@Model.Series.Year</li>
                        </ul>
                        <ul>
                            @foreach (var genre in Model.Series.Genres)
                            {
                                <li>@genre</li>
                            }
                        </ul>
                        <ul>
                            <li>@Model.Series.Runtime minutes</li>
                        </ul>
                    </div>
                </div>

                <p class="overview">@Model.Series.Overview</p>

                <div class="ratings">
                    <span title="The Movie Database rating">
                        <i class="fas fa-star"></i>
                        <span class="rating">@(Model.Series.Ratings.Value % 1 != 0 ? Model.Series.Ratings.Value.ToString() : Model.Series.Ratings.Value.ToString() + ",0")</span>
                        <span class="totalvotes">/ @Model.Series.Ratings.Votes votes</span>
                    </span>
                </div>

                @*<div class="button-block">
                    <ul>
                        <li><a class="btn btn-primary" asp-action="Trailer" asp-controller="Movie" asp-route-ytid="@Model.Movie.youTubeTrailerId" method="get" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#trailer-container" data-ajax-method="get" data-ajax-loading=".loading">Watch trailer <i class="fab fa-youtube"></i></a></li>
                        <partial name="_RequestMovieButton" model="@Model" />
                    </ul>
                </div>*@
            </div>
        </div>
        <div class="body">
            @* Trailer Container *@
            @*<div id="trailer-container"></div>*@
            <div id="container">
                <section class="details">
                    <partial name="_CreditsPartial" model="Model.Cast" />
                </section>  
            </div>
            <div hidden class="loading"><img src="~/img/loading.gif" /></div>

            @foreach (var season in Model.Series.Seasons)
	        {
	            <div style="border:1px solid lightgrey;padding:2rem;border-radius:25px">
                    <h3>Season @season.SeasonNumber</h3>
                </div>
	        }
        </div>
    </section>

    
</div>

<div class="mobile-button-block">
    <ul>
        <li>@*<a class="btn btn-primary" href="@("https://www.youtube.com/watch?v=" + Model.Movie.youTubeTrailerId)">Watch trailer <i class="fab fa-youtube"></i></a>*@</li>
        @if (Model.Accepted || Model.AlreadyAdded)
        {
            <li><a class="btn btn-disabled">Already added <i class="fas fa-plus"></i></a></li>
        }
        else if (Model.Requested)
        {
            <li><a class="btn btn-disabled">Pending approval <i class="fas fa-plus"></i></a></li>
        }
        else
        {
            <li><a class="btn btn-default" asp-action="AddRequest" asp-controller="Request" asp-route-tmdbid="">Request series <i class="fas fa-plus"></i></a></li>
        }
    </ul>
</div>

@*<script>
    $(document).ready(function () {
        let navBtn = $('.page-nav > .body-nav > li');
        navBtn.first().children('a').toggleClass('active');
        navBtn.first().children('a').click();

        navBtn.on('click', function () {
            $('#container').children().first().remove();
            $('.loading').show();
            navBtn.children('a').removeClass('active');
            $(this).children('a').addClass('active');
        })

        let btnBlock = $('.mobile-button-block > ul > li');

        $(document).scroll(function () {
            if (window.scrollY >= 150) {
                btnBlock.children().removeClass('btn')
                btnBlock.children().addClass('btn-sm')
            }

            if (window.scrollY < 150) {
                btnBlock.children().removeClass('btn-sm')
                btnBlock.children().addClass('btn')
            }
        })
    });
</script>*@

MediaRequest/Views/Television/Show.cshtml
@using MediaRequest.WebUI.Business.Services
@inject IImageProcessorService ImageProcessor
@using Microsoft.FeatureManagement 
@inject IFeatureManager FeatureManager

@model MediaRequest.WebUI.ViewModels.Television.SeriesViewModel

<div class="single-movie-container" id="main-container">
    <div class="hero-container">
        <partial name="_Fanart" model="Model.SonarrSeries" />
    </div>
    <section class="container px-xs-1 px-sm-2 px-md-3">
        <div class="head">
            <div class="poster">
                <partial name="_Poster" model="Model.SonarrSeries" />
            </div>
            <div class="info pt-xs-2 pt-lg-0">
                <div class="title">
                    <h1 style="color:#222;">@Model.SonarrSeries.Title</h1>
                    <div class="trivia py-lg-1">
                        <ul>
                            <li>@Model.SonarrSeries.Year</li>
                        </ul>
                        <ul>
                            @foreach (var genre in Model.SonarrSeries.Genres)
                            {
                                <li>@genre</li>
                            }
                        </ul>
                        <ul>
                            <li>@Model.SonarrSeries.Runtime minutes</li>
                        </ul>
                    </div>
                </div>

                <p class="overview">@Model.SonarrSeries.Overview</p>

                <div class="ratings">
                    <span title="The Movie Database rating">
                        <i class="fas fa-star"></i>
                        <span class="rating">@(Model.SonarrSeries.Ratings.Value % 1 != 0 ? Model.SonarrSeries.Ratings.Value.ToString() : Model.SonarrSeries.Ratings.Value.ToString() + ",0")</span>
                        <span class="totalvotes">/ @Model.SonarrSeries.Ratings.Votes votes</span>
                    </span>
                </div>
            </div>
        </div>
            <div class="body">
                @if (await FeatureManager.IsEnabledAsync("TheMovieDB"))
                {
                    <div id="container">
                        <section class="details">
                            <partial name="_CreditsPartial" model="Model.Cast" />
                        </section>
                    </div>
                    <div hidden class="loading"><img src="~/img/loading.gif" /></div>
                }

                @foreach (var season in Model.SonarrSeries.Seasons)
                {
                    <div style="border:1px solid lightgrey;padding:2rem;border-radius:25px">
                        <h3>Season @season.SeasonNumber @season.Statistics.EpisodeCount/@season.Statistics.TotalEpisodeCount</h3>
                    </div>
                }
            </div>
    </section>
</div>

<div class="mobile-button-block">
    <ul>
        @if (Model.Accepted || Model.AlreadyAdded)
        {
            <li><a class="btn btn-disabled">Already added <i class="fas fa-plus"></i></a></li>
        }
        else if (Model.Requested)
        {
            <li><a class="btn btn-disabled">Pending approval <i class="fas fa-plus"></i></a></li>
        }
        else
        {
            <li><a class="btn btn-default" asp-action="AddRequest" asp-controller="Request" asp-route-tmdbid="">Request series <i class="fas fa-plus"></i></a></li>
        }
    </ul>
</div>

MediaRequest/Views/Television/_CreditsPartial.cshtml
@model MediaRequest.WebUI.ViewModels.Television.SeriesCreditViewModel

<section class="cast">
    <h1>Top billed cast</h1>
    <ul class="top-billed">
        @foreach (var member in Model.TopBilled)
        {
            <partial name="_ActorPartial" , model="@member" />
        }
    </ul>

    <h1>Cast</h1>
    <ul class="cast-list">
        @foreach (var item in Model.Cast)
        {
            <partial name="_ActorPartial" , model="@item" />
        }

        @if (!(Model.Cast.Count() < 9))
        {
            if (Model.Cast.Count() > 9)
            {
                <li class="loadmore"><a asp-action="Credits" asp-controller="Television" asp-route-mazeid="@Model" asp-route-amount="0" method="get" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#container" data-ajax-method="get">Show less</a></li>
            }
            else
            {
                <li class="loadmore"><a asp-action="Credits" asp-controller="Television" asp-route-mazeid="@Model.TvMazeId" asp-route-amount="1" method="get" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#container" data-ajax-method="get">Show full cast</a></li>
            }
        }

    </ul>

    @*<h1>Crew</h1>
    <ul class="crew-list">
        @foreach (var item in Model.Cast)
        {
            <li>
                <h2>@item.Name</h2>
                <h3>@item.Job</h3>
            </li>
        }
    </ul>*@
</section>